language: haskell

before_install:
  # Installing Z3
  - ./install_z3.sh

  # Getting base library
  - bash base_setup.sh
ghc:
  - "8.2.2"

script:
  - cabal configure --enable-tests
  - cabal build
  # - cabal test -j2