language: haskell

before_install:
  # Installing Z3
  # https://stackoverflow.com/questions/50038634/how-to-set-up-z3-solver-on-travis-ci-machine
  - export Z3=`wget -q -O- http://github.com/Z3Prover/bin/raw/master/nightly | grep 'z3.*x64.*ubuntu.*.zip<' | awk '{print $7}' | awk -F= '{print $2}' | head -1 | awk -F\" '{print $2}'`;
  - echo "Linux Z3 $Z3";

  - export Z3Base=`basename $Z3 .zip`
  - wget --quiet -L -O z3.zip http://github.com/Z3Prover/bin/raw/master/nightly/`basename $Z3`
  - unzip -q z3.zip -d z3_downloaded
  - /bin/rm z3.zip
  - export PATH=$PATH:$PWD/z3_downloaded/$Z3Base/bin
  - z3 --version
ghc:
  - "8.2.2"

script:
  - cabal configure --enable-tests && cabal build && travis_wait 15 cabal test