name: G2

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    run:
      - gcc -v

      # Installing Z3
      - bash install_z3.sh

      # Getting base library
      - bash base_setup.sh
    
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.2.2'
        cabal-version: '2.0.0.1'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests --enable-benchmarks
    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all
    - name: Run tests
      run: cabal test

